replicaCount: 1

image:
  repository: ghcr.io/carmit246/demo-preview-app
  tag: main
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080

containerPort: 8080

serviceAccount:
  create: true
  name: demo-app-workload

env:
  appEnv: main
  prNumber: ""
  commitSha: main
  awsRegion: us-east-2
  s3BucketName: carmit-techgym-bucket
