apiVersion: s3.aws.crossplane.io/v1beta1
kind: Bucket
metadata:
  name: {{ .Values.env.s3BucketName }}
  namespace: crossplane-system
  annotations:
    crossplane.io/external-name: {{ .Values.env.s3BucketName }}
spec:
  providerConfigRef:
    name: default
    kind: ProviderConfig
  forProvider:
    locationConstraint: us-east-2
    tags:
      demo: crossplane-demo
      owner: devops
