apiVersion: s3.aws.m.upbound.io/v1beta1
kind: Bucket
metadata:
  name: demo-app-bucket
  namespace: crossplane-system
  annotations:
    crossplane.io/external-name: {{ .Values.env.s3BucketName }}
spec:
  providerConfigRef:
    name: default
  forProvider:
    region: us-east-2
    tags:
      demo: crossplane-demo
      owner: devops
